/********************************************************************************
 * project     Tracker statuses                                                 *
 *                                                                              *
 * file        MainWindow.h                                                     *
 * author      Dmitriy Bassamykin                                               *
 * date        12.12.2019                                                       *
 * copyright   The MIT License (MIT). Copyright (c) 2019 Dmitriy Bassamykin     *
 *                                                                              *
 ********************************************************************************/

// -*- C++ -*-
//
// generated by wxGlade 0.9.4 on Thu Dec 12 10:46:42 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MainWindow: public wxFrame {
public:
    // begin wxGlade: MainWindow::ids
    // end wxGlade

    MainWindow(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    void updateNavisetStatus(void);
    void updateNavtelecomStatus(void);

protected:
    // begin wxGlade: MainWindow::attributes
    wxSpinCtrl* spinNavtelecomStatus;
    wxStaticText* lblNavtelecomGsm;
    wxStaticText* lblNavtelecomUsb;
    wxStaticText* lblNavtelecomHiResGps;
    wxStaticText* lblNavtelecomTimeSync;
    wxStaticText* lblNavtelecomSim;
    wxStaticText* lblNavtelecomGsmReg;
    wxStaticText* lblNavtelecomRouming;
    wxStaticText* lblNavtelecomGenerator;
    wxPanel* tabNavtelecom;
    wxSpinCtrl* spinNavisetStatus;
    wxStaticText* lblNavisetPwrExt;
    wxStaticText* lblNavisetMove;
    wxStaticText* lblNavisetSecurity;
    wxStaticText* lblNavisetGsm;
    wxStaticText* lblNavisetGprs;
    wxStaticText* lblNavisetGps;
    wxPanel* tabNaviset;
    wxNotebook* tabTrackers;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void onSpinNavtelecomHandler(wxSpinEvent &event); // wxGlade: <event_handler>
    void onSpinNavtelecomTextHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void onSpinNavisetHandler(wxSpinEvent &event); // wxGlade: <event_handler>
    void onSpinStatusNavisetHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void onSpinNavisetTextHandler(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MAINWINDOW_H
