/********************************************************************************
 * project     Tracker statuses                                                 *
 *                                                                              *
 * file        main.cpp                                                   *
 * author      Dmitriy Bassamykin                                               *
 * date        12.12.2019                                                       *
 * copyright   The MIT License (MIT). Copyright (c) 2019 Dmitriy Bassamykin     *
 *                                                                              *
 ********************************************************************************/
 
// -*- C++ -*-
//
// generated by wxGlade 0.9.4 on Mon Dec 23 16:18:39 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

// This is an automatically generated file.
// Manual changes will be overwritten without warning!

#include <wx/wx.h>
#include <wx/image.h>
#include "MainWindow.h"


class TrackerStatuses: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(TrackerStatuses)

bool TrackerStatuses::OnInit()
{
    wxInitAllImageHandlers();
    MainWindow* frame = new MainWindow(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame);
    frame->Show();
    return true;
}
